### for authentication you, first you should request the code
POST {{api}}/barbers/auth/request
Accept: application/json
Content-Type: application/json

{"phone": "09146878528"}


### then you should send authentication code to this endpoint to get token
POST {{api}}/barbers/auth/verify
Accept: application/json
Content-Type: application/json

{"phone": "09146878528", "code":  "7054"}
