### get shops paginated
# limit: number of returned documents
# threshold: default is 5
#     finds documents which have:
#         (query.lat < document.lat + threshold) AND (query.lat > document.lat - threshold)
#         (query.lng < document.lng + threshold) AND (query.lng > document.lng - threshold)
GET {{api}}/shops
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "limit":  1,
    "threshold": 50.9,
    "lat": 50,
    "lng": 50
}

### get shop by id
GET {{api}}/shops/1
Accept: application/json
Authorization: Bearer {{token}}

### update shop by id
PATCH {{api}}/shops/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "prepayment_amount": "2000",
    "lat": "-23.2314"
}

### delete shop by id
DELETE {{api}}/shops/1
Accept: application/json
Authorization: Bearer {{token}}
