### show all reservations of this service of this baber
GET {{api}}/shops/1/barbers/1/services/1/reservations
Accept: application/json
Authorization: Bearer {{token}}

### get a reservation by id
GET {{api}}/shops/1/barbers/1/services/1/reservations/1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

### create new reservation [only users]
POST {{api}}/shops/1/barbers/1/services/1/reservations
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "start_at": "1621938600"
}

### delete a reservation by id
DELETE {{api}}/shops/1/barbers/1/services/1/reservations/1
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json
